name: web_whiteboard
description: A whiteboard to draw on in the web.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  test: ^1.17.3
